GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/1

###

DELETE http://localhost:3001/api/persons/1

###



POST https://fso21-osa3-puhelinluettelo.herokuapp.com/api/persons
Content-Type:application/json

{
    "name":"ttappe Repo",
    "number":"050-123"
}